# Generated by Django 2.1 on 2018-10-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('activated', models.BooleanField()),
                ('user_token', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('U', 'standard'), ('S', 'setter'), ('A', 'admin')], default='U', max_length=10)),
                ('questions_solved', models.IntegerField(default=0, editable=False)),
                ('bio', models.CharField(default='', max_length=2000)),
                ('contactno', models.IntegerField(blank=True, max_length=10, null=True)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
            ],
        ),
    ]
