# Generated by Django 2.1 on 2018-10-28 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 29, 4, 28, 43, 404873)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2018, 10, 29, 4, 28, 43, 404913)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 29, 1, 28, 43, 404841)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2018, 10, 29, 1, 28, 43, 404894)),
        ),
    ]
