# Generated by Django 2.1.2 on 2018-10-31 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20181028_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 9, 20, 29, 161108)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 1, 9, 20, 29, 161150)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 6, 20, 29, 161075)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 1, 6, 20, 29, 161131)),
        ),
    ]
