# Generated by Django 2.1 on 2018-10-31 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20181031_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 7, 32, 19, 704142)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 1, 7, 32, 19, 704178)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 4, 32, 19, 704114)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 1, 4, 32, 19, 704162)),
        ),
    ]
